# Generated by Django 4.2.5 on 2024-07-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='roles',
            new_name='role',
        ),
    ]
