# Generated by Django 4.2.5 on 2024-07-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_roles_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='user_type',
            field=models.CharField(default='base_user', max_length=100),
        ),
    ]
