# Generated by Django 4.2.5 on 2024-07-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
