# Generated by Django 4.2.5 on 2024-10-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='Remark',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='pcs',
            field=models.IntegerField(default=0),
        ),
    ]
