# Generated by Django 4.2.5 on 2024-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_purchase_order_for_raw_material_cutting_items_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_raw_material_cutting',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
