# Generated by Django 4.2.5 on 2024-10-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_purchase_order_raw_material_cutting_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_cutting_items',
            name='Remark',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labour_workout_cutting_items',
            name='pcs',
            field=models.IntegerField(default=0),
        ),
    ]
