# Generated by Django 4.2.5 on 2024-10-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_labour_workout_childs_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_to_product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation'),
        ),
    ]
