# Generated by Django 4.2.5 on 2024-10-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pproduct_creation',
            name='PProduct_SKU',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_HSNCode',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Refrence_ID',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
