# Generated by Django 4.2.5 on 2024-11-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_pproduct_creation_pproduct_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour_workin_approval_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('difference_qty', models.IntegerField()),
                ('labour_w_i_p_2_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_w_in_products_records', to='product.labour_work_in_product_to_item')),
            ],
        ),
    ]
