# Generated by Django 4.2.5 on 2024-11-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_labour_workin_approval_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workin_approval_report',
            name='unique_id',
            field=models.UUIDField(default=2),
            preserve_default=False,
        ),
    ]
