# Generated by Django 4.2.5 on 2024-11-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_labour_workin_approval_report_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_work_in_product_to_item',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
