# Generated by Django 4.2.5 on 2024-11-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_labour_work_in_product_to_item_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour_work_in_product_to_item',
            name='created_date',
        ),
    ]
