# Generated by Django 4.2.5 on 2024-11-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_raw_material_product_ref_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_material_product_ref_items',
            old_name='raw_material_estination_master',
            new_name='raw_material_estimation_master',
        ),
    ]
