# Generated by Django 4.2.5 on 2024-11-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_raw_material_estination_master_raw_material_product_ref_items_raw_material_estimation_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_material_product_ref_items',
            name='raw_material_estimation_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_production_estimations', to='product.raw_material_production_estimation'),
        ),
        migrations.AlterField(
            model_name='raw_material_product_to_items',
            name='raw_material_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_product_ref_itemss_p_2_i', to='product.raw_material_product_ref_items'),
        ),
        migrations.AlterField(
            model_name='raw_material_product_wise_qty',
            name='raw_material_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_product_ref_itemss', to='product.raw_material_product_ref_items'),
        ),
        migrations.AlterField(
            model_name='raw_material_production_total',
            name='raw_material_estination_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_production_estimations_total', to='product.raw_material_production_estimation'),
        ),
    ]
