# Generated by Django 4.2.5 on 2024-11-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_raw_material_production_total_stock_in_cutting_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_material_production_total',
            name='stock_in_cutting_stage',
        ),
        migrations.RemoveField(
            model_name='raw_material_production_total',
            name='stock_in_labour_workout_stage',
        ),
    ]
