# Generated by Django 4.2.5 on 2024-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_raw_material_production_total_stock_in_cutting_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_material_production_total',
            name='stock_in_cutting_stage',
        ),
        migrations.RemoveField(
            model_name='raw_material_production_total',
            name='stock_in_labour_workout_stage',
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
