# Generated by Django 4.2.5 on 2024-11-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_product_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_goods_warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name_finished', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_purchase_voucher_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=100, unique=True)),
                ('supplier_invoice_number', models.CharField(max_length=100)),
                ('ledger_type', models.CharField(default='purchase', max_length=20)),
                ('fright_transport', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='product_purchase_voucher_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
                ('product_purchase_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_purchase_voucher_master')),
            ],
        ),
        migrations.CreateModel(
            name='Product_warehouse_quantity_through_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.finished_goods_warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
