# Generated by Django 4.2.5 on 2024-11-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_finished_goods_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_purchase_voucher_master',
            name='finished_godowns',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='product.finished_goods_warehouse'),
            preserve_default=False,
        ),
    ]
