# Generated by Django 4.2.5 on 2024-11-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_purchase_voucher_master_finished_godowns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_goods_Stock_TransferMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_warehouse', to='product.finished_goods_warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_warehouse', to='product.godown_finished_goods')),
            ],
        ),
        migrations.AlterField(
            model_name='product_purchase_voucher_master',
            name='ledger_type',
            field=models.CharField(default='purchase(product)', max_length=20),
        ),
        migrations.CreateModel(
            name='Finished_goods_transfer_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity_transfer', models.DecimalField(decimal_places=3, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Finished_goods_Stock_TransferMasterinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.finished_goods_stock_transfermaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
            ],
        ),
    ]
