# Generated by Django 4.2.5 on 2024-11-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_finished_goods_stock_transfermaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods_transfer_records',
            name='product_quantity_transfer',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_purchase_voucher_items',
            name='quantity_total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_purchase_voucher_master',
            name='grand_total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_purchase_voucher_master',
            name='gross_total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product_warehouse_quantity_through_table',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
