# Generated by Django 4.2.5 on 2024-11-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_finished_goods_transfer_records_product_quantity_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_purchase_voucher_master',
            name='grand_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_purchase_voucher_master',
            name='gross_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
