# Generated by Django 4.2.5 on 2024-11-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_purchase_voucher_master_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_warehouse_quantity_through_table',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
