# Generated by Django 4.2.5 on 2024-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_warehouse_quantity_through_table_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_goods_stock_transfermaster',
            name='transnfer_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finished_goods_transfer_records',
            name='transnfer_cancelled_records',
            field=models.BooleanField(default=False),
        ),
    ]
