# Generated by Django 4.2.5 on 2024-11-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_labour_work_in_product_to_item_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown_item_report_for_cutting_room',
            name='cutting_pk',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godown_item_report_for_cutting_room',
            name='p_o_id',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='godown_item_report_for_cutting_room',
            name='product_ref_no',
            field=models.PositiveBigIntegerField(default=3),
            preserve_default=False,
        ),
    ]
