# Generated by Django 4.2.5 on 2024-11-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_godown_item_report_for_cutting_room_cutting_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_goods_stock_transfermaster',
            name='actions',
            field=models.CharField(choices=[('Hold', 'Hold'), ('Cancelled', 'Cancelled'), ('Inward Process', 'Inward Process')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_goods_transfer_records',
            name='diffrence_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_goods_transfer_records',
            name='qc_recieved_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_purchase_voucher_items',
            name='diffrence_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_purchase_voucher_items',
            name='qc_recieved_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_purchase_voucher_master',
            name='actions',
            field=models.CharField(choices=[('Hold', 'Hold'), ('Cancelled', 'Cancelled'), ('Inward Process', 'Inward Process')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
