# Generated by Django 4.2.5 on 2024-11-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_finished_goods_stock_transfermaster_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods_transfer_records',
            name='qc_recieved_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finished_goods_transfer_records',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_purchase_voucher_items',
            name='qc_recieved_qty',
            field=models.IntegerField(default=0),
        ),
    ]
