# Generated by Django 4.2.5 on 2024-11-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_finished_goods_transfer_records_qc_recieved_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished_goods_transfer_records',
            name='diffrence_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_purchase_voucher_items',
            name='diffrence_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
