# Generated by Django 4.2.5 on 2024-11-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_finished_goods_transfer_records_diffrence_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finished_goods_warehouse_racks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='finished_product_warehouse_bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_name', models.CharField(max_length=30, unique=True)),
                ('rack_finished_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='product.finished_goods_warehouse_racks')),
            ],
        ),
        migrations.CreateModel(
            name='finishedgoodsbinallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_serial_no', models.CharField(max_length=50, unique=True)),
                ('source_type', models.CharField(choices=[('purchase', 'Purchase'), ('transfer', 'Transfer')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bin_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.finished_product_warehouse_bin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation')),
                ('related_purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product_purchase_voucher_items')),
                ('related_transfer_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.finished_goods_transfer_records')),
            ],
        ),
        migrations.CreateModel(
            name='finished_goods_warehouse_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=30, unique=True)),
                ('warehouse_finished_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='product.finished_goods_warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='finished_goods_warehouse_racks',
            name='zone_finished_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='product.finished_goods_warehouse_zone'),
        ),
    ]
