# Generated by Django 4.2.5 on 2024-12-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_finishedgoodsbinallocation_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='finished_product_warehouse_bin',
            name='product_size_in_bin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finished_product_warehouse_bin',
            name='sub_catergory_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='product.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finishedgoodsbinallocation',
            name='unique_serial_no',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_color_image',
            field=models.ImageField(blank=True, null=True, upload_to='rawmaterial/images'),
        ),
    ]
