# Generated by Django 4.2.5 on 2024-12-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_finished_product_warehouse_bin_product_size_in_bin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='PProduct_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pproduct_creation'),
        ),
    ]
