# Generated by Django 4.2.5 on 2024-12-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_purchase_order_master_for_puchase_voucher_rm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_puchase_voucher_rm',
            name='master_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order_master_for_puchase_voucher_rm'),
            preserve_default=False,
        ),
    ]
