# Generated by Django 4.2.5 on 2024-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_purchase_order_master_for_puchase_voucher_rm_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_material_production_estimation',
            name='narration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
