# Generated by Django 4.2.5 on 2024-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_raw_material_production_estimation_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_master_for_puchase_voucher_rm',
            name='fright_transport',
            field=models.IntegerField(default=0),
        ),
    ]
