# Generated by Django 4.2.5 on 2024-12-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_purchase_order_master_for_puchase_voucher_rm_fright_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_puchase_voucher_rm',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_puchase_voucher_rm',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_master_for_puchase_voucher_rm',
            name='fright_transport',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
