# Generated by Django 4.2.5 on 2024-07-01 11:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_group', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sub_group', models.CharField(max_length=50, unique=True)),
                ('acc_grp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.accountgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['color_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('Gst_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)])),
            ],
        ),
        migrations.CreateModel(
            name='Fabric_Group_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fab_grp_name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fab_grp_name'],
            },
        ),
        migrations.CreateModel(
            name='FabricFinishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_finish', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['fabric_finish'],
            },
        ),
        migrations.CreateModel(
            name='factory_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_emp_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Godown_finished_goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_name_finished', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Godown_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_name_raw', models.CharField(max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_percentage', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['gst_percentage'],
            },
        ),
        migrations.CreateModel(
            name='item_color_shade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('item_shade_name', models.CharField(max_length=100)),
                ('item_color_image', models.ImageField(upload_to='rawmaterial/images')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('Material_code', models.CharField(max_length=255)),
                ('Units', models.DecimalField(decimal_places=2, default=39.37, max_digits=10)),
                ('Panha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fabric_nonfabric', models.CharField(choices=[('Fabric', 'Fabric'), ('Non Fabric', 'Non Fabric')], max_length=255)),
                ('HSN_Code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Unused', 'Unused'), ('Used', 'Used'), ('Slow Moving', 'Slow Moving'), ('Dead', 'Dead')], max_length=50)),
                ('item_shade_image', models.ImageField(blank=True, null=True, upload_to='rawmaterial/images')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('Fabric_Group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.fabric_group_model')),
                ('Item_Color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemColor', to='product.color')),
                ('Item_Creation_GST', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.gst')),
                ('Item_Fabric_Finishes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.fabricfinishes')),
            ],
        ),
        migrations.CreateModel(
            name='item_purchase_voucher_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=100, unique=True)),
                ('supplier_invoice_number', models.CharField(max_length=100)),
                ('ledger_type', models.CharField(default='purchase', max_length=20)),
                ('fright_transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('vendor_code', models.CharField(blank=True, max_length=100)),
                ('maintain_billwise', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('default_credit_period', models.CharField(blank=True, max_length=100)),
                ('types', models.CharField(blank=True, choices=[('Trader', 'Trader'), ('Manufacture', 'Manufacture')], max_length=30)),
                ('Gst_no', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)])),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('pincode', models.IntegerField()),
                ('mobile_no', models.BigIntegerField()),
                ('landline_no', models.BigIntegerField()),
                ('bank_details', models.TextField(blank=True)),
                ('Debit_Credit', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('N/A', 'N/A')], max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('under_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.accountsubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_material', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['packing_material'],
            },
        ),
        migrations.CreateModel(
            name='PProduct_Creation',
            fields=[
                ('PProduct_image', models.ImageField(blank=True, upload_to='pproduct/images')),
                ('PProduct_SKU', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Product_EANCode', models.CharField(blank=True, max_length=100)),
                ('Product_Rating', models.FloatField(blank=True, null=True)),
                ('Amazon_Link', models.URLField(blank=True)),
                ('Flipkart_Link', models.URLField(blank=True)),
                ('Cosmus_link', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('PProduct_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_primary_color', to='product.color')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('Model_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_Brand', models.CharField(blank=True, choices=[('Cosmus', 'Cosmus'), ('Killer', 'Killer'), ('Tuffgear', 'Tuffgear'), ('BeeArmour', 'BeeArmour'), ('INIT', 'INIT'), ('OEM', 'OEM')], max_length=200, null=True)),
                ('Product_Status', models.CharField(blank=True, choices=[('Preproduction', 'Preproduction'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Discontinued', 'Discontinued')], max_length=100, null=True)),
                ('Product_Channel', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ecommerce', 'Ecommerce'), ('Retail', 'Retail'), ('Corporate', 'Corporate'), ('Modern Trade', ' Modern Trade'), ('Export', ' Export')], max_length=100)),
                ('Product_Refrence_ID', models.PositiveIntegerField(null=True, unique=True)),
                ('Product_Cost_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Product_MRP', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Product_SalePrice_CustomerPrice', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Product_BulkPrice', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Product_WarrantyTime', models.CharField(blank=True, choices=[('0 Months', '0 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('18 Months', '18 Months'), ('24 Months', '24 Months'), ('30 Months', '30 Months'), ('36 Months', '36 Months'), ('42 Months', '42 Months'), ('48 Months', '48 Months'), ('54 Months', '54 Months'), ('60 Months', '60 Months')], max_length=15, null=True)),
                ('Product_HSNCode', models.BigIntegerField(blank=True, null=True)),
                ('Product_ShortName', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_Compartments', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=50, null=True)),
                ('Product_UOM', models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Set of 3', 'Set of 3')], max_length=50, null=True)),
                ('Product_Accessory_Compartments', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=20, null=True)),
                ('Product_CapacityLtrs', models.PositiveIntegerField(blank=True, null=True)),
                ('Product_Material', models.CharField(blank=True, choices=[('PU Coated Polyester', 'PU Coated Polyester'), ('PU Coated Nylon', 'PU Coated Nylon'), ('Vegan Leather', 'Vegan Leather'), ('Polycarbonate', 'Polycarbonate'), ('Eva Shell', 'Eva Shell'), ('Cotton', 'Cotton'), ('Jute', 'Jute')], max_length=100, null=True)),
                ('Product_BulletPoint1', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint2', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint3', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint4', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint5', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_ShortDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_LongDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_Dimensions_WP_Length', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WP_Width', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WP_Height', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WP_Weight', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Length', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Width', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Height', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Weight', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_WRP', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_CashCounterPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_IndiaMartPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_Retailer_dealer_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_Wholesaler_DistributorPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_Create_Date', models.DateField(auto_now=True)),
                ('Product_Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=15, null=True)),
                ('Product_QtyPerBox', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('Product_GST', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.gst')),
            ],
        ),
        migrations.CreateModel(
            name='product_2_item_through_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('common_unique', models.BooleanField(default=False)),
                ('no_of_rows', models.IntegerField(default=1)),
                ('Remark', models.CharField(blank=True, max_length=100, null=True)),
                ('Item_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_creation')),
                ('PProduct_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pproduct_creation')),
            ],
            options={
                'unique_together': {('PProduct_pk', 'Item_pk')},
            },
        ),
        migrations.CreateModel(
            name='purchase_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.IntegerField(unique=True)),
                ('target_date', models.DateField()),
                ('created_date', models.DateField(auto_now=True)),
                ('modified_created_date', models.DateField(auto_now_add=True)),
                ('number_of_pieces', models.IntegerField(default=0)),
                ('process_status', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True)),
                ('ledger_party_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
                ('product_reference_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_voucher_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_directly', models.BooleanField(default=False)),
                ('item_purchase_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_purchase_voucher_master')),
                ('item_shade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade')),
            ],
        ),
        migrations.CreateModel(
            name='RawStockTransferMaster',
            fields=[
                ('voucher_no', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('destination_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_godowns', to='product.godown_raw_material')),
                ('source_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_godowns', to='product.godown_raw_material')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Name_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sub_category_name', models.CharField(max_length=250)),
                ('product_main_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.maincategory')),
            ],
            options={
                'unique_together': {('product_sub_category_name', 'product_main_category')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_item_name', models.CharField(max_length=150, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('acc_sub_grp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.accountsubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='shade_godown_items_temporary_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField()),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('godown_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.godown_raw_material')),
            ],
        ),
        migrations.CreateModel(
            name='shade_godown_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deleted_directly', models.BooleanField(default=False)),
                ('godown_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.godown_raw_material')),
                ('purchase_voucher_godown_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_voucher_items')),
            ],
        ),
        migrations.CreateModel(
            name='set_prod_item_part_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=100, null=True)),
                ('part_dimentions', models.CharField(blank=True, max_length=100, null=True)),
                ('dimention_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('part_pieces', models.IntegerField(blank=True, null=True)),
                ('producttoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_configs', to='product.product_2_item_through_table')),
            ],
        ),
        migrations.CreateModel(
            name='RawStockTrasferRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity_transfer', models.DecimalField(decimal_places=3, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('item_shade_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_color_shade')),
                ('master_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.rawstocktransfermaster')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order_to_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField(default=0)),
                ('process_quantity', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pproduct_creation')),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order_raw_material_cutting',
            fields=[
                ('raw_material_cutting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('factory_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.factory_employee')),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order_for_raw_material_cutting_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panha', models.DecimalField(decimal_places=3, max_digits=10)),
                ('units', models.DecimalField(decimal_places=3, max_digits=10)),
                ('g_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_comsumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance_physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cutting_quantity', models.IntegerField(default=0)),
                ('purchase_order_cutting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order_raw_material_cutting')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order_for_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.DecimalField(decimal_places=3, max_digits=10)),
                ('g_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_comsumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance_physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideoUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_video_url', models.URLField(blank=True, max_length=255)),
                ('Image_Uploaded_at', models.DateTimeField(auto_now=True)),
                ('Image_Modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvideourls', to='product.pproduct_creation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='product/images')),
                ('Image_type', models.CharField(blank=True, choices=[('Main Image', 'Main Image'), ('White Background', 'White Background'), ('Model Image', 'Model Image'), ('Catalogue Image', 'Catalogue Image')], max_length=100)),
                ('Order_by', models.IntegerField(blank=True)),
                ('Image_Uploaded_at', models.DateTimeField(auto_now=True)),
                ('Image_Modified_at', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='product.pproduct_creation')),
            ],
        ),
        migrations.CreateModel(
            name='Product_A_plus_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('orderby', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='pproduct/images')),
                ('dimensions', models.CharField(choices=[('200 * 200', '200 * 200'), ('1260 * 200', '1260 * 200'), ('1080 * 720', '1080 * 720')], max_length=70)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productaplus', to='product.pproduct_creation')),
            ],
        ),
        migrations.AddField(
            model_name='pproduct_creation',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetails', to='product.product'),
        ),
        migrations.CreateModel(
            name='opening_shade_godown_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('opening_rate', models.DecimalField(decimal_places=1, max_digits=10)),
                ('opening_godown_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.godown_raw_material')),
                ('opening_purchase_voucher_godown_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_color_shade')),
            ],
        ),
        migrations.CreateModel(
            name='item_shades_godown_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(auto_now_add=True)),
                ('particulars', models.CharField(max_length=150)),
                ('voucher_type', models.CharField(max_length=150)),
                ('voucher_no', models.IntegerField()),
                ('inward_outward', models.CharField(choices=[('inward', 'inward'), ('outward', 'outward')], max_length=50)),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_shade_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade')),
            ],
        ),
        migrations.AddField(
            model_name='item_purchase_voucher_master',
            name='party_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger'),
        ),
        migrations.AddField(
            model_name='item_creation',
            name='Item_Packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.packaging'),
        ),
        migrations.AddField(
            model_name='item_creation',
            name='unit_name_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.unit_name_create'),
        ),
        migrations.AddField(
            model_name='item_color_shade',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='product.item_creation'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='account_credit_debit_master_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('voucher_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('voucher_type', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entry', to='product.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Product2SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_cats', to='product.product')),
                ('SubCategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.subcategory')),
            ],
            options={
                'unique_together': {('Product_id', 'SubCategory_id')},
            },
        ),
        migrations.CreateModel(
            name='item_godown_quantity_through_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Item_shade_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='godown_shades', to='product.item_color_shade')),
                ('godown_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_godown_names', to='product.godown_raw_material')),
            ],
            options={
                'unique_together': {('godown_name', 'Item_shade_name')},
            },
        ),
    ]
