# Generated by Django 4.2.5 on 2024-03-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawstocktransfer',
            name='date_and_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
