# Generated by Django 4.2.5 on 2024-02-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
