# Generated by Django 4.2.5 on 2024-01-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_Name',
            fields=[
                ('unit_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item_creation',
            name='Fabric_Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.fabric_group_model'),
        ),
        migrations.AlterField(
            model_name='item_creation',
            name='Item_Color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ItemColor', to='product.color'),
        ),
        migrations.AlterField(
            model_name='item_creation',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_name'),
        ),
        migrations.AlterField(
            model_name='item_creation',
            name='Unit_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.unit_name'),
        ),
    ]
