# Generated by Django 4.2.5 on 2024-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_2_item_through_table',
            options={'ordering': ['row_number']},
        ),
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='row_number',
            field=models.IntegerField(null=True),
        ),
    ]
