# Generated by Django 4.2.5 on 2024-03-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godown_finished_goods',
            name='godown_name_finished',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='godown_raw_material',
            name='godown_name_raw',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
