# Generated by Django 4.2.5 on 2024-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='dimention_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='part_dimentions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='part_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='part_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
