# Generated by Django 4.2.5 on 2024-07-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='cutting_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
