# Generated by Django 4.2.5 on 2024-02-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item_godown_quantity_through_table',
            unique_together=set(),
        ),
    ]
