# Generated by Django 4.2.5 on 2024-03-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_product_category_name',
            new_name='product_sub_category_name',
        ),
    ]
