# Generated by Django 4.2.5 on 2024-04-04 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_purchase_voucher_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=100, unique=True)),
                ('supplier_invoice_number', models.CharField(max_length=100)),
                ('ledger_type', models.CharField(default='purchase', max_length=20)),
                ('fright_transport', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gst_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.gst')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_voucher_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item_purchase_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_purchase_voucher_master')),
                ('item_shade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade')),
            ],
        ),
        migrations.CreateModel(
            name='shade_godown_items_temporary_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('godown_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RenameField(
            model_name='account_credit_debit_master_table',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='item_godown_quantity_through_table',
            name='item_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledger',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledger',
            name='modified_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='godown_finished_goods',
            name='godown_name_finished',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='godown_raw_material',
            name='godown_name_raw',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='product2subcategory',
            unique_together={('Product_id', 'SubCategory_id')},
        ),
        migrations.CreateModel(
            name='shade_godown_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('godown_select', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.godown_raw_material')),
                ('purchase_voucher_godown_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_voucher_items')),
            ],
        ),
        migrations.CreateModel(
            name='item_shades_godown_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(auto_now_add=True)),
                ('particulars', models.CharField(max_length=150)),
                ('voucher_type', models.CharField(max_length=150)),
                ('voucher_no', models.IntegerField()),
                ('inward_outward', models.CharField(choices=[('inward', 'inward'), ('outward', 'outward')], max_length=50)),
                ('Quantity', models.IntegerField()),
                ('item_shade_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade')),
            ],
        ),
        migrations.AddField(
            model_name='item_purchase_voucher_master',
            name='party_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger'),
        ),
    ]
