# Generated by Django 4.2.5 on 2024-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_creation',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='rawmaterial/images'),
        ),
    ]
