# Generated by Django 4.2.5 on 2024-04-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shade_godown_items_temporary_table',
            name='godown_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.godown_raw_material'),
        ),
    ]
