# Generated by Django 4.2.5 on 2024-05-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_2_item_through_table',
            name='set_prod_config',
        ),
        migrations.AddField(
            model_name='set_prod_item_part_name',
            name='set_prod_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_item_configs', to='product.product_2_item_through_table'),
            preserve_default=False,
        ),
    ]
