# Generated by Django 4.2.5 on 2024-02-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_creation',
            name='HSN_Code',
            field=models.CharField(blank=True, default=34, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item_creation',
            name='Material_code',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
