# Generated by Django 4.2.5 on 2024-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricfinishes',
            name='fabric_finish',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gst',
            name='gst_percentage',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packing_material',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
