# Generated by Django 4.2.5 on 2024-03-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pproduct_creation',
            name='product_Video_URL',
        ),
        migrations.CreateModel(
            name='ProductVideoUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_video_url', models.URLField(blank=True, max_length=255, null=True)),
                ('Image_Uploaded_at', models.DateTimeField(auto_now=True)),
                ('Image_Modified_at', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productvideourls', to='product.pproduct_creation')),
            ],
        ),
    ]
