# Generated by Django 4.2.5 on 2024-02-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_godown_quantity_through_table_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item_godown_quantity_through_table',
            unique_together={('godown_name', 'Item_shade_name')},
        ),
    ]
