# Generated by Django 4.2.5 on 2024-04-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_shade_godown_items_temporary_table_godown_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_voucher_items',
            old_name='quantity',
            new_name='quantity_total',
        ),
    ]
