# Generated by Django 4.2.5 on 2024-03-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_godown_finished_goods_godown_name_finished_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shade_godown_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('godown_select', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.godown_raw_material')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_voucher_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('quantity_total', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item_shade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade')),
            ],
        ),
        migrations.CreateModel(
            name='item_shades_godown_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(auto_now_add=True)),
                ('particulars', models.CharField(max_length=150)),
                ('voucher_type', models.CharField(max_length=150)),
                ('voucher_no', models.IntegerField()),
                ('inward_outward', models.CharField(choices=[('inward', 'inward'), ('outward', 'outward')], max_length=50)),
                ('Quantity', models.IntegerField()),
                ('item_shade_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade')),
            ],
        ),
        migrations.CreateModel(
            name='item_purchase_voucher_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.IntegerField()),
                ('supplier_invoice_number', models.IntegerField()),
                ('ledger_type', models.CharField(max_length=150)),
                ('fright_transport', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gst_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.gst')),
                ('party_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
            ],
        ),
    ]
