# Generated by Django 4.2.5 on 2024-09-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_account_credit_debit_master_table_credit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyMaster',
        ),
    ]
