# Generated by Django 4.2.5 on 2024-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_color_shade_item_name_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_name_rank',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
