# Generated by Django 4.2.5 on 2024-02-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_creation_hsn_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_GST',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.gst'),
        ),
    ]
