# Generated by Django 4.2.5 on 2024-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_refrence_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_creation',
            name='rate',
        ),
        migrations.AddField(
            model_name='item_color_shade',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
