# Generated by Django 4.2.5 on 2024-04-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_fabricfinishes_fabric_finish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_voucher_items',
            old_name='quantity_total',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='shade_godown_items_temporary_table',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='item_purchase_voucher_master',
            name='gst_rate',
        ),
        migrations.AlterField(
            model_name='product2subcategory',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_cats', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product2subcategory',
            name='SubCategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='product.maincategory'),
        ),
    ]
