# Generated by Django 4.2.5 on 2024-03-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_sub_product_category_name_subcategory_product_sub_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='product_main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.maincategory'),
        ),
    ]
