# Generated by Django 4.2.5 on 2024-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_2_item_through_table_set_prod_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='part_pieces',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
