# Generated by Django 4.2.5 on 2024-02-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_color_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_name_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
