# Generated by Django 4.2.5 on 2024-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_capacityltrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_CapacityLtrs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
