# Generated by Django 4.2.5 on 2024-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_set_prod_item_part_name_dimention_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='dimention_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
