# Generated by Django 4.2.5 on 2024-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_subcategory_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='product_sub_category_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('id', 'product_main_category')},
        ),
    ]
