# Generated by Django 4.2.5 on 2024-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_purchase_order_for_raw_material_cutting_items_cutting_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
