# Generated by Django 4.2.5 on 2024-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_color_shade_item_shade_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_creation',
            name='item_color_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
