# Generated by Django 4.2.5 on 2024-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_creation_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_creation',
            old_name='Description',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='item_creation',
            name='Name',
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Accessory_Compartments',
            field=models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Height',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Length',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Width',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Height',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Length',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Width',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_EANCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_ShortName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(blank=True, choices=[('Preproduction', 'Preproduction'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Discontinued', 'Discontinued')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_WarrantyCode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='item_name',
        ),
    ]
