# Generated by Django 4.2.5 on 2024-07-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_item_creation_rate_item_color_shade_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutting_room',
            name='cutting_room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item_creation',
            name='Fabric_Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='product.fabric_group_model'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
