# Generated by Django 4.2.5 on 2024-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_subcategory_product_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='product_sub_category_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
