# Generated by Django 4.2.5 on 2024-03-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_item_color_shade_item_name_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Model_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_BulletPoint1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_BulletPoint2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_BulletPoint3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_BulletPoint4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_BulletPoint5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_CapacityLtrs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_CashCounterPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Compartments',
            field=models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Height',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Length',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WOP_Width',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Height',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Length',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Dimensions_WP_Width',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_HSNCode',
            field=models.BigIntegerField(blank=True, default='12345678', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_IndiaMartPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_LongDescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Material',
            field=models.CharField(blank=True, choices=[('PU Coated Polyester', 'PU Coated Polyester'), ('PU Coated Nylon', 'PU Coated Nylon'), ('Vegan Leather', 'Vegan Leather'), ('Polycarbonate', 'Polycarbonate'), ('Eva Shell', 'Eva Shell'), ('Cotton', 'Cotton'), ('Jute', 'Jute')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_QtyPerBox',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Refrence_ID',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Retailer_dealer_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_ShortDescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_ShortName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_UOM',
            field=models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Set of 3', 'Set of 3')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_WRP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Wholesaler_DistributorPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
