# Generated by Django 4.2.5 on 2024-05-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_set_prod_item_part_name_part_pieces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set_prod_item_part_name',
            old_name='set_prod_config',
            new_name='producttoitem',
        ),
    ]
