# Generated by Django 4.2.5 on 2024-04-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_fabric_group_model_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
