# Generated by Django 4.2.5 on 2024-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_item_color_shade_item_name_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_creation',
            name='HSN_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
