# Generated by Django 4.2.5 on 2024-02-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_description_item_creation_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_color_shade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_rank', models.IntegerField(blank=True, null=True)),
                ('item_shade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_color_image', models.ImageField(blank=True, null=True, upload_to='rawmaterial/images')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='product.item_creation')),
            ],
        ),
    ]
