# Generated by Django 4.2.5 on 2024-04-18 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_quantity_purchase_voucher_items_quantity_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('Gst_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)])),
            ],
        ),
        migrations.AlterField(
            model_name='shade_godown_items_temporary_table',
            name='unique_id',
            field=models.UUIDField(),
        ),
    ]
