# Generated by Django 4.2.5 on 2024-05-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_set_prod_item_part_name_dimention_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_2_item_through_table',
            name='row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
