# Generated by Django 4.2.5 on 2024-02-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_product_capacityltrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
