# Generated by Django 4.2.5 on 2024-04-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_item_creation_item_color_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_color_shade',
            name='item_shade_quantity',
        ),
        migrations.RemoveField(
            model_name='item_creation',
            name='item_color_quantity',
        ),
        migrations.CreateModel(
            name='opening_shade_godown_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opening_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_godown_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.godown_raw_material')),
                ('opening_purchase_voucher_godown_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_color_shade')),
            ],
        ),
    ]
