# Generated by Django 4.2.5 on 2024-03-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_shade_godown_items_purchase_voucher_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_voucher_items',
            name='item_purchase_master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.item_purchase_voucher_master'),
            preserve_default=False,
        ),
    ]
