# Generated by Django 4.2.5 on 2024-02-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_item_godown_quantity_through_table_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawStockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.BigIntegerField()),
                ('item_name_transfer', models.CharField(max_length=200)),
                ('item_color_transfer', models.CharField(max_length=200)),
                ('item_shade_transfer', models.CharField(max_length=200)),
                ('item_quantity_transfer', models.CharField(max_length=200)),
                ('item_unit_transfer', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
