# Generated by Django 4.2.5 on 2024-03-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_subcategory_product_sub_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='product_category_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
