# Generated by Django 4.2.5 on 2024-10-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_labour_workout_cutting_items_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_childs',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
