# Generated by Django 4.2.5 on 2024-07-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_purchase_order_for_raw_material_cutting_items_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_raw_material_cutting',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order'),
        ),
    ]
