# Generated by Django 4.2.5 on 2024-07-24 12:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cutting_room_cutting_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_godown_quantity_through_table',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item_godown_quantity_through_table',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening_shade_godown_quantity',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opening_shade_godown_quantity',
            name='modified_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_voucher_items',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase_voucher_items',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='item_godown_inward_outward_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.IntegerField()),
                ('voucher_type', models.CharField(max_length=100)),
                ('particular', models.CharField(max_length=100)),
                ('inward', models.IntegerField()),
                ('outward', models.IntegerField()),
                ('item_shade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_color_shade')),
            ],
        ),
    ]
