# Generated by Django 4.2.5 on 2024-02-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_item_creation_hsn_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sub_group', models.CharField(max_length=50)),
                ('acc_grp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.accountgroup')),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_item_name', models.CharField(max_length=150)),
                ('acc_sub_grp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.accountsubgroup')),
            ],
        ),
    ]
