# Generated by Django 4.2.5 on 2024-03-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rawstocktransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_godown_quantity_through_table',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
