# Generated by Django 4.2.5 on 2024-04-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_item_color_shade_item_shade_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening_shade_godown_quantity',
            name='opening_amount',
        ),
    ]
