# Generated by Django 4.2.5 on 2024-03-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pproduct_creation',
            name='Product_Rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
