# Generated by Django 4.2.5 on 2024-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_subcategory_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='gst_percentage',
            field=models.IntegerField(),
        ),
    ]
