# Generated by Django 4.2.5 on 2024-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_set_prod_config_set_prod_item_part_name_producttoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_2_item_through_table',
            name='row_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
