# Generated by Django 4.2.5 on 2024-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_labour_charges_alter_ledger_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='process_status',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, null=True),
        ),
    ]
