# Generated by Django 4.2.5 on 2024-03-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_purchase_voucher_items_item_purchase_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_voucher_items',
            name='serial_no',
        ),
    ]
