# Generated by Django 4.2.5 on 2024-05-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_2_item_through_table_row_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_color_image',
            field=models.ImageField(default='static/images/default_image.jpg', upload_to='rawmaterial/images'),
        ),
    ]
