# Generated by Django 4.2.5 on 2024-09-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_labour_workout_childs_labour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_work_in_master',
            name='total_balance_pcs',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
