# Generated by Django 4.2.5 on 2024-04-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_companymaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shade_godown_items',
            old_name='godown_select',
            new_name='godown_id',
        ),
        migrations.RenameField(
            model_name='shade_godown_items_temporary_table',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
