# Generated by Django 4.2.5 on 2024-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_MRP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
