# Generated by Django 4.2.5 on 2024-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_opening_shade_godown_quantity_opening_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening_shade_godown_quantity',
            name='opening_quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='opening_shade_godown_quantity',
            name='opening_rate',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
