# Generated by Django 4.2.5 on 2024-04-06 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_gst_gst_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Gst_no',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
