# Generated by Django 4.2.5 on 2024-05-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_2_item_through_table_row_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='row_number',
            field=models.IntegerField(null=True),
        ),
    ]
