# Generated by Django 4.2.5 on 2024-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_godown_quantity_through_table_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_godown_inward_outward_master',
            name='inward',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_godown_inward_outward_master',
            name='outward',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_godown_inward_outward_master',
            name='voucher_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_godown_inward_outward_master',
            name='voucher_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
