# Generated by Django 4.2.5 on 2024-07-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_purchase_order_raw_material_cutting_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='temp_godown_select',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.godown_raw_material'),
            preserve_default=False,
        ),
    ]
