# Generated by Django 4.2.5 on 2024-09-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_purchase_order_process_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour_work_in_master',
            name='labour_name',
        ),
    ]
