# Generated by Django 4.2.5 on 2024-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_godown_select_shade_godown_items_godown_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_voucher_items',
            name='quantity_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shade_godown_items',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shade_godown_items_temporary_table',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
