# Generated by Django 4.2.5 on 2024-02-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_product_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Model_Name',
            field=models.CharField(blank=True, default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Brand',
            field=models.CharField(blank=True, choices=[('Cosmus', 'Cosmus'), ('Killer', 'Killer'), ('Tuffgear', 'Tuffgear'), ('BeeArmour', 'BeeArmour'), ('INIT', 'INIT'), ('OEM', 'OEM')], default='Cosmus', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_GST',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to='product.gst'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Name',
            field=models.CharField(blank=True, default='testi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(blank=True, choices=[('Preproduction', 'Preproduction'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Discontinued', 'Discontinued')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_WarrantyTime',
            field=models.CharField(blank=True, choices=[('0 Months', '0 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('18 Months', '18 Months'), ('24 Months', '24 Months'), ('30 Months', '30 Months'), ('36 Months', '36 Months'), ('42 Months', '42 Months'), ('48 Months', '48 Months'), ('54 Months', '54 Months'), ('60 Months', '60 Months')], default='0 Months', max_length=15),
        ),
    ]
