# Generated by Django 4.2.5 on 2024-03-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_pproduct_creation_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
