# Generated by Django 4.2.5 on 2024-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_labour_work_in_master_total_balance_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_work_in_product_to_item',
            name='approved_qty',
            field=models.IntegerField(default=0),
        ),
    ]
