# Generated by Django 4.2.5 on 2024-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_product_bulkprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
