# Generated by Django 4.2.5 on 2024-03-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_color_image',
            field=models.ImageField(blank=True, null=True, upload_to='rawmaterial/images'),
        ),
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_name_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_shade_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
