# Generated by Django 4.2.5 on 2024-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_purchase_voucher_items_quantity_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_voucher_items',
            name='quantity_total',
            field=models.IntegerField(),
        ),
    ]
