# Generated by Django 4.2.5 on 2024-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_opening_shade_godown_quantity_opening_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shade_godown_items_temporary_table',
            name='unique_id',
            field=models.CharField(max_length=150),
        ),
    ]
