# Generated by Django 4.2.5 on 2024-04-06 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_ledger_gst_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='Gst_no',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
