# Generated by Django 4.2.5 on 2024-02-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_model_name_alter_product_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_GST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.gst'),
        ),
    ]
