# Generated by Django 4.2.5 on 2024-03-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_item_purchase_voucher_master_ledger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shade_godown_items',
            name='purchase_voucher_godown_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.purchase_voucher_items'),
            preserve_default=False,
        ),
    ]
