# Generated by Django 4.2.5 on 2024-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_labour_work_in_master_labour_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour_work_in_master',
            name='total_pcs',
        ),
        migrations.RemoveField(
            model_name='labour_work_in_master',
            name='total_pending_pcs',
        ),
        migrations.AddField(
            model_name='labour_workout_childs',
            name='labour_workin_pcs',
            field=models.IntegerField(default=0),
        ),
    ]
