# Generated by Django 4.2.5 on 2024-07-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_item_godown_inward_outward_master_inward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_voucher_items',
            name='item_purchase_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_items', to='product.item_purchase_voucher_master'),
        ),
        migrations.AlterField(
            model_name='shade_godown_items',
            name='purchase_voucher_godown_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godown_items', to='product.purchase_voucher_items'),
        ),
    ]
