# Generated by Django 4.2.5 on 2024-05-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_2_item_through_table_row_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_2_item_through_table',
            options={'ordering': ('row_number',)},
        ),
    ]
