# Generated by Django 4.2.5 on 2024-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_purchase_order_temp_godown_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_raw_material_cutting',
            name='balance_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_order_raw_material_cutting',
            name='processed_qty',
            field=models.IntegerField(default=0),
        ),
    ]
