# Generated by Django 4.2.5 on 2024-04-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_shade_godown_items_temporary_table_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shade_godown_items_temporary_table',
            name='unique_id',
            field=models.UUIDField(),
        ),
    ]
