# Generated by Django 4.2.5 on 2024-02-24 08:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Amazon_Link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Cosmus_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Flipkart_Link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Accessory_Compartments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_BulletPoint1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_BulletPoint2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_BulletPoint3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_BulletPoint4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_BulletPoint5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_CapacityLtrs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_CashCounterPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Compartments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WOP_Height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WOP_Length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WOP_Weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WOP_Width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WP_Height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WP_Length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WP_Weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Dimensions_WP_Width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_EANCode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_IndiaMartPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_LongDescription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_ManufacturingDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_MotherWarehouseQty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_ProductionQty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_QtyPerBox',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_ReadyStockFactoryQty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_RetailStoreQty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Retailer_dealer_Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_ShortDescription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_ShortName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_UOM',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Video_URL',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_WRP',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_WarehouseQty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_WarrantyCode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Wholesaler_DistributorPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Youtube_Link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_primary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_tertiary',
        ),
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_color_image',
            field=models.ImageField(blank=True, null=True, upload_to='rawmaterial/images'),
        ),
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_name_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_shade_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item_creation',
            name='item_shade_image',
            field=models.ImageField(blank=True, null=True, upload_to='rawmaterial/images'),
        ),
        migrations.AlterField(
            model_name='pproduct_creation',
            name='PProduct_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_primary_color', to='product.color'),
        ),
        migrations.AlterField(
            model_name='pproduct_creation',
            name='PProduct_image',
            field=models.ImageField(blank=True, null=True, upload_to='pproduct/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_BulkPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Channel',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ecommerce', 'Ecommerce'), ('Retail', 'Retail'), ('Corporate', 'Corporate'), ('Modern Trade', ' Modern Trade'), ('Export', ' Export')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_MRP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_SalePrice_CustomerPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Product_additionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ShortName', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_EANCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Compartments', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=50, null=True)),
                ('Product_UOM', models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Set of 3', 'Set of 3')], max_length=50, null=True)),
                ('Product_Accessory_Compartments', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=20, null=True)),
                ('Product_CapacityLtrs', models.PositiveIntegerField(blank=True, null=True)),
                ('Product_Material', models.CharField(blank=True, choices=[('PU Coated Polyester', 'PU Coated Polyester'), ('PU Coated Nylon', 'PU Coated Nylon'), ('Vegan Leather', 'Vegan Leather'), ('Polycarbonate', 'Polycarbonate'), ('Eva Shell', 'Eva Shell'), ('Cotton', 'Cotton'), ('Jute', 'Jute')], max_length=100, null=True)),
                ('Product_BulletPoint1', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint2', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint3', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint4', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_BulletPoint5', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_ShortDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_LongDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_Dimensions_WP_Length', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WP_Width', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WP_Height', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WP_Weight', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Length', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Width', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Height', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Dimensions_WOP_Weight', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_WRP', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_CashCounterPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_IndiaMartPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_Retailer_dealer_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_Wholesaler_DistributorPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Product_Video_URL', models.CharField(blank=True, max_length=255, null=True)),
                ('Product_ProductionQty', models.IntegerField(blank=True, null=True)),
                ('Product_ReadyStockFactoryQty', models.IntegerField(blank=True, null=True)),
                ('Product_MotherWarehouseQty', models.IntegerField(blank=True, null=True)),
                ('Product_WarehouseQty', models.IntegerField(blank=True, null=True)),
                ('Product_RetailStoreQty', models.IntegerField(blank=True, null=True)),
                ('Product_ManufacturingDate', models.DateField(auto_now_add=True)),
                ('Product_WarrantyCode', models.CharField(blank=True, max_length=150, null=True)),
                ('Product_Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=15, null=True)),
                ('Product_Rating', models.FloatField(blank=True, null=True)),
                ('Amazon_Link', models.URLField(blank=True, null=True)),
                ('Flipkart_Link', models.URLField(blank=True, null=True)),
                ('Cosmus_link', models.URLField(blank=True, null=True)),
                ('Youtube_Link', models.URLField(blank=True, null=True)),
                ('Product_QtyPerBox', models.IntegerField(blank=True, null=True)),
                ('color_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_color', to='product.color')),
                ('color_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_color', to='product.color')),
                ('color_tertiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tertiary_color', to='product.color')),
            ],
        ),
    ]
