# Generated by Django 4.2.5 on 2024-09-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customuser_is_admin'),
        ('product', '0007_accountgroup_c_user_accountsubgroup_c_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='godown_finished_goods',
            name='godown_name_finished',
            field=models.CharField(max_length=225),
        ),
    ]
