# Generated by Django 4.2.5 on 2024-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_item_color_shade_item_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_color_image',
            field=models.ImageField(default='defaultimages/default_image.jpg', upload_to='rawmaterial/images'),
        ),
    ]
