# Generated by Django 4.2.5 on 2024-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_item_color_shade_item_color_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_HSNCode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Product_A_plus_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('orderby', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='pproduct/images')),
                ('dimensions', models.CharField(choices=[('200 * 200', '200 * 200'), ('1260 * 200', '1260 * 200'), ('1080 * 720', '1080 * 720')], max_length=70)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productaplus', to='product.pproduct_creation')),
            ],
        ),
    ]
