# Generated by Django 4.2.5 on 2024-07-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_purchase_voucher_items_item_purchase_master_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_godown_inward_outward_master',
            old_name='date',
            new_name='date_name',
        ),
    ]
