# Generated by Django 4.2.5 on 2024-03-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_shade_godown_items_purchase_voucher_godown_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_voucher_items',
            name='item_shade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_color_shade'),
        ),
        migrations.AlterField(
            model_name='shade_godown_items',
            name='godown_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.godown_raw_material'),
        ),
    ]
