# Generated by Django 4.2.5 on 2024-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_labour_work_in_master_total_pcs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour_work_in_master',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labour_work_in_master',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
