# Generated by Django 4.2.5 on 2024-07-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_purchase_order_raw_material_cutting_balance_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='balance_number_of_pieces',
            field=models.IntegerField(default=0),
        ),
    ]
