# Generated by Django 4.2.5 on 2024-05-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_shade_godown_items_temporary_table_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_credit_debit_master_table',
            name='account_name',
        ),
    ]
