# Generated by Django 4.2.5 on 2024-07-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_date_item_godown_inward_outward_master_date_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_voucher_items',
            name='item_purchase_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_purchase_voucher_master'),
        ),
        migrations.AlterField(
            model_name='shade_godown_items',
            name='purchase_voucher_godown_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_voucher_items'),
        ),
    ]
