# Generated by Django 4.2.5 on 2024-09-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_labour_work_in_master_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_childs',
            name='labour_workin_pending_pcs',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
