# Generated by Django 4.2.5 on 2024-02-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_product_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_creation',
            name='item_shade_image',
            field=models.ImageField(blank=True, null=True, upload_to='rawmaterial/images'),
        ),
    ]
