# Generated by Django 4.2.5 on 2024-03-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_purchase_voucher_items_item_shade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_purchase_voucher_master',
            name='purchase_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='purchase_voucher_items',
            name='item_shade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade'),
        ),
        migrations.AlterField(
            model_name='shade_godown_items',
            name='godown_select',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.godown_raw_material'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase_voucher_items',
            unique_together={('item_purchase_master', 'item_shade')},
        ),
    ]
