# Generated by Django 4.2.5 on 2024-09-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_stockitem_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroup',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='accountsubgroup',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='color',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='fabric_group_model',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='fabricfinishes',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='gst',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='item_color_shade',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='item_creation',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='ledgertypes',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='opening_shade_godown_quantity',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='pproduct_creation',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='product2subcategory',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='product_a_plus_content',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='productvideourls',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='unit_name_create',
            name='c_user',
        ),
    ]
