# Generated by Django 4.2.5 on 2024-03-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_product_hsncode_product_a_plus_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Brand',
            field=models.CharField(blank=True, choices=[('Cosmus', 'Cosmus'), ('Killer', 'Killer'), ('Tuffgear', 'Tuffgear'), ('BeeArmour', 'BeeArmour'), ('INIT', 'INIT'), ('OEM', 'OEM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_BulkPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_GST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.gst'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_MRP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_SalePrice_CustomerPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(blank=True, choices=[('Preproduction', 'Preproduction'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Discontinued', 'Discontinued')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_WarrantyTime',
            field=models.CharField(blank=True, choices=[('0 Months', '0 Months'), ('6 Months', '6 Months'), ('12 Months', '12 Months'), ('18 Months', '18 Months'), ('24 Months', '24 Months'), ('30 Months', '30 Months'), ('36 Months', '36 Months'), ('42 Months', '42 Months'), ('48 Months', '48 Months'), ('54 Months', '54 Months'), ('60 Months', '60 Months')], max_length=15, null=True),
        ),
    ]
