# Generated by Django 4.2.5 on 2024-07-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_purchase_order_balance_number_of_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='balance_number_of_pieces',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
