# Generated by Django 4.2.5 on 2024-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_purchase_order_balance_number_of_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='product_sku',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='product_sku',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
