# Generated by Django 4.2.5 on 2024-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_item_purchase_voucher_master_purchase_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase_voucher_items',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='item_purchase_voucher_master',
            name='purchase_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item_purchase_voucher_master',
            name='supplier_invoice_number',
            field=models.CharField(max_length=100),
        ),
    ]
