# Generated by Django 4.2.5 on 2024-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_labour_workout_childs_labour_workin_pending_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_to_item_labour_child_workout',
            name='labour_w_in_pending',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
