# Generated by Django 4.2.5 on 2024-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_item_color_shade_item_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_creation',
            name='Units',
            field=models.DecimalField(decimal_places=2, default=39.37, max_digits=10),
        ),
    ]
