# Generated by Django 4.2.5 on 2024-09-21 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customuser_is_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_remove_accountgroup_c_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='company_name',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
