# Generated by Django 4.2.10 on 2024-02-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_item_creation_item_shade_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_creation',
            name='item_image',
        ),
    ]
