# Generated by Django 4.2.5 on 2024-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_account_credit_debit_master_table_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='voucher_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
