# Generated by Django 4.2.5 on 2024-09-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_to_item_labour_child_workout_labour_w_in_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour_work_in_product_to_item',
            name='pending_to_return_pcs',
        ),
    ]
