# Generated by Django 4.2.5 on 2024-07-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_purchase_order_for_raw_material_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='process_quantity_cutting',
            field=models.IntegerField(default=0),
        ),
    ]
