# Generated by Django 4.2.5 on 2024-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_account_credit_debit_master_table_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_voucher_items',
            name='deleted_directly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shade_godown_items',
            name='deleted_directly',
            field=models.BooleanField(default=False),
        ),
    ]
