# Generated by Django 4.2.5 on 2024-04-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_purchase_voucher_items_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product2subcategory',
            unique_together={('Product_id', 'SubCategory_id')},
        ),
    ]
