# Generated by Django 4.2.5 on 2024-02-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('product', '0010_remove_item_creation_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True)),
                ('maintain_billwise', models.CharField(blank=True, choices=[('Trader', 'Trader'), ('Manufacture', 'Manufacture')], max_length=30)),
                ('default_credit_period', models.CharField(blank=True, max_length=100)),
                ('types', models.CharField(blank=True, choices=[('Trader', 'Trader'), ('Manufacture', 'Manufacture')], max_length=30)),
                ('Gst_no', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('pincode', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('landline_no', models.IntegerField()),
                ('bank_details', models.CharField(blank=True, max_length=255)),
                ('Debit_Credit', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=255)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('under_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.accountsubgroup')),
            ],
        ),
    ]
