# Generated by Django 4.2.5 on 2024-06-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_item_creation_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.IntegerField(unique=True)),
                ('target_date', models.DateField()),
                ('created_date', models.DateField(auto_now=True)),
                ('modified_created_date', models.DateField(auto_now_add=True)),
                ('number_of_pieces', models.IntegerField(default=0)),
                ('ledger_party_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
                ('product_reference_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
