# Generated by Django 4.2.5 on 2024-07-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_delete_item_godown_inward_outward_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour_workout_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.IntegerField()),
                ('labour_name', models.CharField(default='TESTLABOUR', max_length=50)),
                ('total_approved_pcs', models.IntegerField(default=0)),
                ('total_pending_pcs', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='purchase_order_raw_material_cutting',
            name='approved_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_order_to_product_cutting',
            name='approved_pcs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='product.purchase_order'),
        ),
        migrations.AlterField(
            model_name='purchase_order_raw_material_cutting',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_pos', to='product.purchase_order'),
        ),
        migrations.AlterField(
            model_name='purchase_order_to_product',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_o_to_products', to='product.purchase_order'),
        ),
        migrations.CreateModel(
            name='product_to_item_labour_workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=100)),
                ('approved_pcs', models.IntegerField()),
                ('pending_pcs', models.IntegerField()),
                ('labour_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_workout_items', to='product.labour_workout_master')),
            ],
        ),
        migrations.AddField(
            model_name='labour_workout_master',
            name='purchase_order_cutting_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labourworkouts', to='product.purchase_order_raw_material_cutting'),
        ),
        migrations.CreateModel(
            name='labour_workout_cutting_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=50)),
                ('product_color', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('material_color_shade', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panha', models.DecimalField(decimal_places=3, max_digits=10)),
                ('units', models.DecimalField(decimal_places=3, max_digits=10)),
                ('g_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_comsumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance_physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('labour_workout_master_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.labour_workout_master')),
            ],
        ),
    ]
