# Generated by Django 4.2.5 on 2024-09-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_labour_work_in_product_to_item_pending_to_return_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_work_in_product_to_item',
            name='pending_to_return_pcs',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
