# Generated by Django 4.2.5 on 2024-07-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_purchase_order_for_raw_material_cutting_items_process_quantity_cutting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='cutting_quantity',
        ),
        migrations.CreateModel(
            name='purchase_order_to_product_cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.IntegerField(default=0)),
                ('process_quantity', models.IntegerField(default=0)),
                ('cutting_quantity', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pproduct_creation')),
                ('purchase_order_cutting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order_raw_material_cutting')),
            ],
        ),
    ]
