# Generated by Django 4.2.5 on 2024-06-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_purchase_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_name']},
        ),
        migrations.AlterModelOptions(
            name='gst',
            options={'ordering': ['gst_percentage']},
        ),
    ]
