# Generated by Django 4.2.5 on 2024-02-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_item_color_shade_item_name_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pproduct_creation',
            old_name='Product',
            new_name='Product_Creation',
        ),
    ]
