# Generated by Django 4.2.5 on 2024-05-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_purchase_voucher_items_deleted_directly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_prod_item_part_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('part_dimentions', models.CharField(max_length=100)),
                ('dimention_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('part_pieces', models.IntegerField()),
                ('part_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='product_2_item_through_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Item_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.item_creation')),
                ('PProduct_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pproduct_creation')),
                ('set_prod_config', models.ManyToManyField(to='product.set_prod_item_part_name')),
            ],
        ),
    ]
