# Generated by Django 4.2.5 on 2024-09-23 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_remove_customuser_is_admin'),
        ('product', '0011_alter_stockitem_stock_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown_finished_goods',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.AddField(
            model_name='godown_raw_material',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.AlterField(
            model_name='godown_finished_goods',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='godown_raw_material',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='godown_finished_goods',
            unique_together={('godown_name_finished', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='godown_raw_material',
            unique_together={('godown_name_raw', 'company')},
        ),
    ]
