# Generated by Django 4.2.5 on 2024-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
