# Generated by Django 4.2.5 on 2024-06-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_color_options_alter_gst_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricfinishes',
            options={'ordering': ['fabric_finish']},
        ),
        migrations.AlterModelOptions(
            name='packaging',
            options={'ordering': ['packing_material']},
        ),
    ]
