# Generated by Django 4.2.5 on 2024-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_ledger_address_alter_ledger_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='maintain_billwise',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
    ]
