# Generated by Django 4.2.5 on 2024-02-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_product_pproduct_creation_product_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pproduct_creation',
            old_name='Product_Creation',
            new_name='Product',
        ),
    ]
