# Generated by Django 4.2.5 on 2024-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_purchase_order_for_raw_material_cutting_items_cutting_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='process_quantity_cutting',
        ),
        migrations.RemoveField(
            model_name='purchase_order_to_product_cutting',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchase_order_to_product_cutting',
            name='product_color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_to_product_cutting',
            name='product_sku',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
