# Generated by Django 4.2.5 on 2024-05-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_set_prod_item_part_name_product_2_item_through_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_prod_item_part_name',
            name='location',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='dimention_total',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product_2_item_through_table',
            unique_together={('PProduct_pk', 'Item_pk')},
        ),
    ]
