# Generated by Django 4.2.5 on 2024-09-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_to_item_labour_child_workout_labour_w_in_pcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_to_item_labour_child_workout',
            name='labour_w_in_pcs',
        ),
    ]
