# Generated by Django 4.2.5 on 2024-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_purchase_order_to_product_cutting_balance_pcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_to_product_cutting',
            name='approved_pcs_diffrence',
            field=models.IntegerField(default=0),
        ),
    ]
