# Generated by Django 4.2.5 on 2024-07-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_purchase_order_for_raw_material_cutting_items_process_quantity_cutting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='material_color_shade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade'),
            preserve_default=False,
        ),
    ]
