# Generated by Django 4.2.5 on 2024-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_product_creation_pproduct_creation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='landline_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pproduct_creation',
            name='PProduct_SKU',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_HSNCode',
            field=models.BigIntegerField(blank=True, default='12345678'),
        ),
    ]
