# Generated by Django 4.2.5 on 2024-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_set_prod_item_part_name_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Number_of_items',
            field=models.IntegerField(default=0),
        ),
    ]
