# Generated by Django 4.2.5 on 2024-06-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_fabricfinishes_options_alter_packaging_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric_group_model',
            options={'ordering': ['fab_grp_name']},
        ),
        migrations.AlterModelOptions(
            name='unit_name_create',
            options={'ordering': ['unit_name']},
        ),
    ]
