# Generated by Django 4.2.5 on 2024-09-23 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_maincategory_c_user_pproduct_creation_c_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_prod_item_part_name',
            name='c_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
