# Generated by Django 4.2.5 on 2024-08-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_purchase_order_to_product_cutting_approved_pcs_diffrence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_to_item_labour_workout',
            old_name='approved_pcs',
            new_name='processed_pcs',
        ),
    ]
