# Generated by Django 4.2.5 on 2024-02-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_ledger_landline_no_alter_ledger_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_additionals',
            name='Product_ManufacturingDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='account_credit_debit_master_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_name', models.CharField(max_length=100)),
                ('voucher_no', models.IntegerField()),
                ('voucher_type', models.IntegerField()),
                ('particulars', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
            ],
        ),
    ]
