# Generated by Django 4.2.5 on 2024-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_to_item_labour_child_workout_labour_w_in_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_to_item_labour_child_workout',
            name='labour_w_in_pcs',
            field=models.IntegerField(default=0),
        ),
    ]
