# Generated by Django 4.2.5 on 2024-07-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_purchase_order_for_raw_material_cutting_items_material_color_shade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='material_color_shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade'),
        ),
    ]
