# Generated by Django 4.2.5 on 2024-06-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rawstocktransfermaster_rawstocktrasferrecords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawstocktrasferrecords',
            name='item_color_transfer',
        ),
        migrations.RemoveField(
            model_name='rawstocktrasferrecords',
            name='item_name_transfer',
        ),
        migrations.AlterField(
            model_name='rawstocktrasferrecords',
            name='item_shade_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_color_shade'),
        ),
    ]
