# Generated by Django 4.2.5 on 2024-09-23 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0015_alter_pproduct_creation_c_user_alter_product_c_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product2subcategory',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
