# Generated by Django 4.2.5 on 2024-07-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_purchase_order_for_raw_material_cutting_items_material_color_shade'),
    ]

    operations = [
        migrations.CreateModel(
            name='cutting_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_room_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='factory_employee',
            name='cutting_room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.cutting_room'),
        ),
    ]
