# Generated by Django 4.2.5 on 2024-08-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_approved_pcs_product_to_item_labour_workout_processed_pcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='purchase_order_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
