# Generated by Django 4.2.5 on 2024-02-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_additionals_product_manufacturingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_entry', to='product.ledger'),
        ),
    ]
