# Generated by Django 4.2.5 on 2024-05-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_2_item_through_table_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Number_of_items',
        ),
        migrations.RemoveField(
            model_name='product_2_item_through_table',
            name='location',
        ),
    ]
