# Generated by Django 4.2.5 on 2024-08-03 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_purchase_order_purchase_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour_workout_master',
            name='labour_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='types',
            field=models.CharField(blank=True, choices=[('Trader', 'Trader'), ('Manufacture', 'Manufacture'), ('labour', 'labour')], max_length=30),
        ),
    ]
