# Generated by Django 4.2.5 on 2024-06-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_rawstocktrasferrecords_item_color_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawstocktrasferrecords',
            name='item_unit_transfer',
        ),
    ]
