# Generated by Django 4.2.5 on 2024-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_account_credit_debit_master_table_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='particulars',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='voucher_type',
            field=models.CharField(max_length=100),
        ),
    ]
