# Generated by Django 4.2.5 on 2024-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_cutting_room_factory_employee_cutting_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory_employee',
            name='cutting_room_id',
        ),
        migrations.AlterField(
            model_name='factory_employee',
            name='factory_emp_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='cutting_room',
        ),
    ]
