# Generated by Django 4.2.5 on 2024-05-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_number_of_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_prod_item_part_name',
            name='location',
        ),
    ]
