# Generated by Django 4.2.5 on 2024-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_rawstocktrasferrecords_item_unit_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstocktransfermaster',
            name='voucher_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
