# Generated by Django 4.2.5 on 2024-02-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_account_credit_debit_master_table_particulars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='voucher_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
