# Generated by Django 4.2.5 on 2024-08-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_labour_workout_master_labour_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour_workout_master',
            name='labour_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.ledger'),
        ),
    ]
