# Generated by Django 4.2.5 on 2024-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_set_prod_item_part_name_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_2_item_through_table',
            name='common_unique',
            field=models.BooleanField(default=False),
        ),
    ]
