# Generated by Django 4.2.5 on 2024-09-24 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0018_alter_product_2_item_through_table_c_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product2subcategory',
            name='c_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
