# Generated by Django 4.2.5 on 2024-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_account_credit_debit_master_table_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_name', models.CharField(max_length=100)),
                ('godown_material_name', models.CharField(choices=[('Raw Material', 'Raw Material'), ('Finished Goods', 'Finished Goods')], max_length=100)),
            ],
        ),
    ]
