# Generated by Django 4.2.5 on 2024-06-15 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_rawstocktransfermaster_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_shade_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
