# Generated by Django 4.2.5 on 2024-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_labour_workout_master_labour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour_workout_master',
            name='challan_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
