# Generated by Django 4.2.5 on 2024-02-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_godown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godown',
            name='godown_material_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='item_godown_quantity_through_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('Items_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='godown_items', to='product.item_color_shade')),
                ('godown_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='godown_names', to='product.godown')),
            ],
        ),
    ]
