# Generated by Django 4.2.5 on 2024-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_2_item_through_table_common_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='common_unique',
            field=models.BooleanField(default=False),
        ),
    ]
