# Generated by Django 4.2.5 on 2024-08-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_labour_workout_master_challan_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='labour_workout_childs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(unique=True)),
                ('labour_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
                ('labour_workout_master_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.labour_workout_master')),
            ],
        ),
    ]
