# Generated by Django 4.2.5 on 2024-06-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_item_color_shade_item_shade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstocktransfermaster',
            name='destination_godown',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawstocktransfermaster',
            name='source_godown',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rawstocktrasferrecords',
            name='item_quantity_transfer',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawstocktrasferrecords',
            name='item_shade_transfer',
            field=models.IntegerField(),
        ),
    ]
