# Generated by Django 4.2.5 on 2024-09-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_color_c_user_fabric_group_model_c_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='PProduct_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.pproduct_creation'),
        ),
    ]
