# Generated by Django 4.2.5 on 2024-08-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_labour_workout_childs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour_workout_master',
            name='challan_no',
        ),
        migrations.RemoveField(
            model_name='labour_workout_master',
            name='labour_name',
        ),
        migrations.AddField(
            model_name='labour_workout_childs',
            name='total_approved_pcs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labour_workout_childs',
            name='total_pending_pcs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='product_to_item_labour_child_workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=100)),
                ('processed_pcs', models.IntegerField()),
                ('pending_pcs', models.IntegerField()),
                ('labour_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_workout_child_items', to='product.labour_workout_childs')),
            ],
        ),
    ]
