# Generated by Django 4.2.5 on 2024-06-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_rawstocktransfermaster_destination_godown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstocktrasferrecords',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
