# Generated by Django 4.2.5 on 2024-05-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_set_prod_item_part_name_part_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_2_item_through_table',
            old_name='part_type',
            new_name='Remark',
        ),
    ]
