# Generated by Django 4.2.5 on 2024-06-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_rawstocktrasferrecords_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawstocktransfermaster',
            name='destination_godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_godowns', to='product.godown_raw_material'),
        ),
        migrations.AlterField(
            model_name='rawstocktransfermaster',
            name='source_godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_godowns', to='product.godown_raw_material'),
        ),
        migrations.AlterField(
            model_name='rawstocktrasferrecords',
            name='item_shade_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item_color_shade'),
        ),
    ]
