# Generated by Django 4.2.5 on 2024-08-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_labour_workout_master_challan_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour_workout_cutting_items',
            name='labour_workout_master_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.labour_workout_childs'),
        ),
    ]
