# Generated by Django 4.2.5 on 2024-02-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_godown_godown_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_color_shade',
            name='item_name_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
