# Generated by Django 4.2.5 on 2024-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_rename_part_type_product_2_item_through_table_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='Remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
