# Generated by Django 4.2.5 on 2024-02-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_item_color_shade_item_name_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_godown_quantity_through_table',
            name='Items_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godown_items', to='product.item_color_shade'),
        ),
    ]
