# Generated by Django 4.2.5 on 2024-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_labour_workout_cutting_items_labour_workout_master_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_childs',
            name='total_balance_pcs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_to_item_labour_child_workout',
            name='balance_pcs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
