# Generated by Django 4.2.5 on 2024-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_labour_workout_childs_total_balance_pcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='cutting_total_processed_qty',
            field=models.IntegerField(default=0),
        ),
    ]
