# Generated by Django 4.2.5 on 2024-10-03 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_set_prod_item_part_name_body_combi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='no_of_rows',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
