# Generated by Django 4.2.5 on 2024-06-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_purchase_voucher_items_item_shade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Debit_Credit',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('N/A', 'N/A')], max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase_voucher_items',
            name='item_shade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.item_color_shade'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='purchase_order_to_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order')),
            ],
        ),
    ]
