# Generated by Django 4.2.5 on 2024-02-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_item_godown_quantity_through_table_items_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_godown_quantity_through_table',
            name='Items_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='godown_items', to='product.item_color_shade'),
        ),
    ]
