# Generated by Django 4.2.5 on 2024-08-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_purchase_order_cutting_total_processed_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour_workout_childs',
            old_name='total_pending_pcs',
            new_name='total_process_pcs',
        ),
    ]
