# Generated by Django 4.2.5 on 2024-06-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_ledger_debit_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_to_product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.pproduct_creation'),
        ),
    ]
