# Generated by Django 4.2.5 on 2024-05-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_2_item_through_table_no_of_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='no_of_rows',
            field=models.IntegerField(default=1),
        ),
    ]
