# Generated by Django 4.2.5 on 2024-06-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_purchase_order_to_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order_to_product',
            old_name='quantity',
            new_name='order_quantity',
        ),
    ]
