# Generated by Django 4.2.5 on 2024-08-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_rename_total_pending_pcs_labour_workout_childs_total_process_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_raw_material_cutting',
            name='cutting_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
