# Generated by Django 4.2.5 on 2024-10-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_godown_finished_goods_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_work_in_master',
            name='total_approved_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='product_godown_quantity_through_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('godown_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_godown_names', to='product.godown_finished_goods')),
                ('product_color_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='godown_colors', to='product.pproduct_creation')),
            ],
            options={
                'unique_together': {('godown_name', 'product_color_name')},
            },
        ),
    ]
