# Generated by Django 4.2.5 on 2024-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_purchase_order_raw_material_cutting_cutting_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='cutting_room_status',
            field=models.CharField(choices=[('cutting_room', 'cutting_room'), ('labour_workout', 'labour_workout')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='purchase_order_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='material_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='product_color',
            field=models.CharField(max_length=60),
        ),
    ]
