# Generated by Django 4.2.5 on 2024-06-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_purchase_order_to_product_process_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_order_for_raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('panha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('g_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_comsuption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('physical_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_physical_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order')),
            ],
        ),
    ]
