# Generated by Django 4.2.5 on 2024-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_labour_work_in_master_total_approved_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_work_in_product_to_item',
            name='pending_for_approval',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
