# Generated by Django 4.2.5 on 2024-08-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_purchase_order_for_raw_material_cutting_room_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_for_raw_material',
            name='cutting_room_status',
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='cutting_room_status',
            field=models.CharField(choices=[('cutting_room', 'cutting_room'), ('labour_workout', 'labour_workout')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
