# Generated by Django 4.2.5 on 2024-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_purchase_order_for_raw_material_cutting_room_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='cutting_room_status',
            field=models.CharField(blank=True, choices=[('cutting_room', 'cutting_room'), ('labour_workout', 'labour_workout')], max_length=20, null=True),
        ),
    ]
