# Generated by Django 4.2.5 on 2024-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_labour_work_in_product_to_item_pending_for_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_2_item_through_table',
            name='grand_total_combi',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product_godown_quantity_through_table',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='body_combi',
            field=models.CharField(blank=True, choices=[('Body', 'Body'), ('Combi', 'Combi')], max_length=10, null=True),
        ),
    ]
