# Generated by Django 4.2.5 on 2024-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_purchase_order_for_raw_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order_for_raw_material',
            old_name='total_comsuption',
            new_name='total_comsumption',
        ),
        migrations.AddField(
            model_name='item_creation',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
