# Generated by Django 4.2.5 on 2024-08-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_purchase_order_for_raw_material_cutting_items_cutting_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='cutting_room_status',
            field=models.CharField(blank=True, choices=[('cutting_room', 'cutting_room'), ('cutting_room_cancelled', 'cutting_room_cancelled'), ('labour_workout', 'labour_workout')], max_length=25, null=True),
        ),
    ]
