# Generated by Django 4.2.5 on 2024-10-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_2_item_through_table_grand_total_combi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set_prod_item_part_name',
            name='body_combi',
            field=models.CharField(blank=True, choices=[('body', 'body'), ('combi', 'combi')], max_length=10, null=True),
        ),
    ]
