# Generated by Django 4.2.5 on 2024-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_purchase_order_for_raw_material_cutting_items_cutting_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_name_create',
            name='unit_value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit_name_create',
            name='unit_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
