# Generated by Django 4.2.5 on 2024-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_item_creation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_BulkPrice',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Cost_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_MRP',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_SalePrice_CustomerPrice',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='balance_physical_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='g_total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='panha',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='physical_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='total_comsumption',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='units',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
