# Generated by Django 4.2.5 on 2024-10-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_set_prod_item_part_name_body_combi'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='g_total_combi',
            field=models.DecimalField(decimal_places=3, default=123, max_digits=10),
            preserve_default=False,
        ),
    ]
