# Generated by Django 4.2.5 on 2024-10-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_purchase_order_for_raw_material_g_total_combi'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_cutting_items',
            name='g_total_combi',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='g_total_combi',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
