# Generated by Django 4.2.5 on 2024-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_unit_name_create_unit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_creation',
            name='Units',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
