# Generated by Django 4.2.5 on 2024-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_product_product_bulkprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='process_status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase_order_to_product',
            name='cutting_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
