# Generated by Django 4.2.5 on 2024-08-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_item_creation_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_cutting_items',
            name='unit_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='unit_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='unit_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
