# Generated by Django 4.2.5 on 2024-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_labour_workout_cutting_items_g_total_combi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_cutting_items',
            name='combi_consumption',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='combi_consumption',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='combi_consumption',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=10),
            preserve_default=False,
        ),
    ]
