# Generated by Django 4.2.5 on 2024-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_purchase_order_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='process_status',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], null=True),
        ),
    ]
