# Generated by Django 4.2.5 on 2024-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_labour_workout_cutting_items_unit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour_workout_cutting_items',
            name='unit_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material',
            name='unit_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='unit_value',
            field=models.CharField(max_length=100),
        ),
    ]
