# Generated by Django 4.2.5 on 2024-10-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_labour_workout_cutting_items_combi_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_to_product',
            name='order_processed_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
