# Generated by Django 4.2.5 on 2024-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_labour_workout_cutting_items_unit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='voucher_no',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
