# Generated by Django 4.2.5 on 2024-10-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_purchase_order_to_product_order_processed_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting_room',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='cutting_room',
            name='company',
        ),
    ]
