# Generated by Django 4.2.5 on 2024-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_purchase_order_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='product_color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
