# Generated by Django 4.2.5 on 2024-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_cutting_room_c_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='remark',
            field=models.CharField(default='body', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_2_item_through_table',
            name='Remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
