# Generated by Django 4.2.5 on 2024-06-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_purchase_order_for_raw_material_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='factory_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_emp_name', models.CharField(max_length=255)),
            ],
        ),
    ]
