# Generated by Django 4.2.5 on 2024-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_account_credit_debit_master_table_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_creation',
            name='Material_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
