# Generated by Django 4.2.5 on 2024-06-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_factory_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory_employee',
            old_name='fac_emp_name',
            new_name='factory_emp_name',
        ),
    ]
