# Generated by Django 4.2.5 on 2024-10-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_purchase_order_for_raw_material_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_order_for_raw_material',
            old_name='remark',
            new_name='Remark',
        ),
    ]
