# Generated by Django 4.2.5 on 2024-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_item_creation_material_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='godown_item_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('particular', models.CharField(max_length=100)),
                ('voucher_type', models.CharField(max_length=100)),
                ('voucher_number', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
