# Generated by Django 4.2.5 on 2024-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_rename_remark_purchase_order_for_raw_material_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material',
            name='pcs',
            field=models.IntegerField(default=0),
        ),
    ]
