# Generated by Django 4.2.5 on 2024-06-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_rename_fac_emp_name_factory_employee_factory_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='factory_employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.factory_employee'),
        ),
    ]
