# Generated by Django 4.2.5 on 2024-10-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_rename_remark_purchase_order_for_raw_material_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory_employee',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='factory_employee',
            name='company',
        ),
    ]
