# Generated by Django 4.2.5 on 2024-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_godown_item_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='godown_item_report_for_cutting_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('particular', models.CharField(max_length=100)),
                ('voucher_type', models.CharField(max_length=100)),
                ('voucher_number', models.CharField(max_length=100)),
                ('material_color_shade', models.CharField(max_length=255)),
                ('godown_id', models.CharField(max_length=50)),
                ('inward_outward', models.BooleanField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='godown_item_report',
        ),
    ]
