# Generated by Django 4.2.5 on 2024-08-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_godown_item_report_for_cutting_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='godown_item_report_for_cutting_room',
            old_name='inward_outward',
            new_name='inward',
        ),
    ]
