# Generated by Django 4.2.5 on 2024-07-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_remove_purchase_order_factory_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_order_for_raw_material_cutting_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=100)),
                ('material_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panha', models.DecimalField(decimal_places=3, max_digits=10)),
                ('units', models.DecimalField(decimal_places=3, max_digits=10)),
                ('g_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_comsumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('balance_physical_stock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cutting_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_order_raw_material_cutting',
            fields=[
                ('raw_material_cutting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('factory_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.factory_employee')),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.purchase_order')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase_order_to_product',
            name='cutting_quantity',
        ),
        migrations.DeleteModel(
            name='purchase_order_for_raw_material_cutting',
        ),
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='purchase_order_cutting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order_raw_material_cutting'),
        ),
    ]
