# Generated by Django 4.2.5 on 2024-08-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_rename_inward_outward_godown_item_report_for_cutting_room_inward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='godown_item_report_for_cutting_room',
            old_name='quantity',
            new_name='total_comsumption',
        ),
    ]
