# Generated by Django 4.2.5 on 2024-08-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_rename_quantity_godown_item_report_for_cutting_room_total_comsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour_workout_childs',
            name='total_approved_pcs',
        ),
        migrations.RemoveField(
            model_name='labour_workout_childs',
            name='total_balance_pcs',
        ),
        migrations.AlterField(
            model_name='godown_item_report_for_cutting_room',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
