# Generated by Django 4.2.5 on 2024-08-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_remove_labour_workout_childs_total_approved_pcs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour_workout_childs',
            name='total_balance_pcs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
