# Generated by Django 4.2.5 on 2024-08-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_labour_workout_childs_total_balance_pcs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item_color_shade',
            unique_together={('items', 'item_shade_name')},
        ),
    ]
