# Generated by Django 4.2.5 on 2024-08-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_item_color_shade_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour_workout_cutting_items',
            old_name='labour_workout_master_instance',
            new_name='labour_workout_child_instance',
        ),
    ]
