# Generated by Django 4.2.5 on 2024-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_rename_labour_workout_master_instance_labour_workout_cutting_items_labour_workout_child_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='total_comsumption_in_cutting',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
