# Generated by Django 4.2.5 on 2024-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_purchase_order_for_raw_material_cutting_items_total_comsumption_in_cutting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='cutting_room_status',
            field=models.CharField(blank=True, choices=[('cutting_room', 'cutting_room'), ('cutting_room_cancelled', 'cutting_room_cancelled')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='total_comsumption_in_cutting',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
