# Generated by Django 4.2.5 on 2024-08-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_alter_purchase_order_for_raw_material_cutting_items_cutting_room_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Model_Name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase_order_raw_material_cutting',
            name='raw_material_cutting_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='labour_work_in_master',
            fields=[
                ('voucher_number', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('labour_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ledger')),
                ('labour_voucher_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.labour_workout_childs')),
            ],
        ),
    ]
