# Generated by Django 4.2.5 on 2024-08-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_product_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_raw_material_cutting',
            name='auto_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_order_raw_material_cutting',
            name='raw_material_cutting_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
