# Generated by Django 4.2.5 on 2024-08-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_purchase_order_raw_material_cutting_auto_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase_order_raw_material_cutting',
            options={'ordering': ['auto_id']},
        ),
    ]
