# Generated by Django 4.2.5 on 2024-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_purchase_order_raw_material_cutting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_for_raw_material_cutting_items',
            name='total_comsumption_in_cutting',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
