# Generated by Django 4.2.5 on 2024-08-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_godown_item_report_for_cutting_room_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_credit_debit_master_table',
            name='voucher_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
