# Generated by Django 4.2.5 on 2024-08-26 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_alter_account_credit_debit_master_table_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='number_of_pieces',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
