# Generated by Django 4.2.5 on 2024-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_alter_purchase_order_number_of_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order_to_product',
            name='purchase_order_to_product_saved',
            field=models.BooleanField(default=False),
        ),
    ]
