# Generated by Django 4.2.5 on 2024-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_purchase_order_to_product_purchase_order_to_product_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_to_product',
            name='purchase_order_to_product_saved',
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='purchase_order_to_product_saved',
            field=models.BooleanField(default=False),
        ),
    ]
