# Generated by Django 4.2.5 on 2024-08-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_labour_work_in_master_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_color_shade',
            options={'ordering': ['items__item_name']},
        ),
    ]
