# Generated by Django 4.2.5 on 2024-08-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_item_color_shade_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledgerTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ledger',
            name='types',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='product.ledgertypes'),
        ),
    ]
